### ISSUE TITLE
Softlock due to failed randomizer logic?

### ISSUE THREAD

**Issue by CherrehBomb** [LagoLunatic/wwrando#101]
I'm at a point where I'm unable to continue.  I need the grappling hook and another bow progression item and they're both in the Cabana Labyrinth.

[WW Random PunishedLink - Spoiler Log.txt](https://github.com/LagoLunatic/wwrando/files/2786789/WW.Random.PunishedLink.-.Spoiler.Log.txt)

4:
  Private Oasis:
      Cabana Labyrinth - First Chest:                    Progressive Bow
      Cabana Labyrinth - Second Chest:                   Grappling Hook

As far as I know, you _need_ the grappling hook to pull the lever in the cabana that opens the entrance to the Labyrinth below.

I don't think I'm missing anything here, so I wanted to share this if I really got a bad seed. 

My permalink is: MS41LjAAUHVuaXNoZWRMaW5rAB8vAwMeAAMBAQ==

I've completed almost all previous progression steps.  What am I missing?

**Comment by JarheadHME** [comment]
Random secret caves. Due to how the randomizer works currently, it displays spoiler log information on where the cave that would be on that island in vanilla. In vanilla, the labyrinth would be on private oasis, so it displays that under private oasis. In actuality though, the actual cabana labyrinth is on bomb island.

**Comment by CherrehBomb** [comment]
Dang, I didn't consider the cabana's basement to be a secret cave.  Thanks.
