### ISSUE TITLE
softlock (all vital items in unreachable locations)

### ISSUE THREAD

**Issue by KLPD123** [LagoLunatic/wwrando#105]
[WW Random thisisthestoryofagirl - Spoiler Log.txt](https://github.com/LagoLunatic/wwrando/files/2818548/WW.Random.thisisthestoryofagirl.-.Spoiler.Log.txt)

I have opened what I believe to be all the chests available to me. I even used my boomerang to defeat the big octos and platform cannons. I cannot access any bombs, power bracelet, wallet upgrades (for triforce charts), bow upgrades, iron boots, hookshot, spoils bag, or delivery bag.
According to the progression log, the game wants me to get the hookshot by watering all the deku trees. I can't access the one on cliff plateau isles because the cave that leads to it is on outset under the headstone which requires bracelets. The power bracelets are in forsaken fortress which require bombs to access. The bomb bags are located by giving marie pendants (spoils bag needed) and in the chuchu cave behind a rock (needs bombs or bracelet). The spoils bag is in dragon roost cavern which is on diamond steppe island, requiring the hookshot. What am I supposed to do?

**Comment by JarheadHME** [comment]
Unfortunately due to a logic error that exists in the current main release, the outset island cave entrance doesn't require you to have power bracelets due to a mistake on Lago's part. This has been fixed for the next version and will likely be coming in a minor release soon (1.5.1), but for now you're just kinda stuck. Unless you want to do some glitches to get where you get bombs. (For the record, the bomb locations you mentioned in the spoiler log are for the *bomb bag* upgrades, not actual bombs. Actual bombs are labeled as just "Bombs").

Now, if you want to continue, depending on the items you have right now, you may have an out. Assuming you have leaf.

If you enter wind temple (which is on horseshoe), you can get past the first actual room but leaf-pumping your way across. This involves, as you're leafing over, putting away the leaf and very quickly pulling it back out. This results in you being able to fly across gaps by not losing as much height as you ordinarily would. So you're flying on the leaf, and on the next frame, you hit the A button to release the leaf, and on the next frame (or one of the few frames following) you pull out the leaf again. This allows you to fly further, as every time you do this you lose a little bit less height than you would ordinarily. Doing this + maybe a ledge grab, will allow you to get across the first room.

The next two rooms you do as usual as there shouldn't be anything different based on the items you have access to.

(Now this next part is dependent on whether I'm misremembering something or not) Then you're in the hub room. Take makar with you to the room behind the armos knights. If I'm remembering right, then you can command melody him over the top of the spinning wall thing and have him step on a switch to make it rotate, and then go into the next room which has the chest with bombs in it.

If I'm *wrong*, then you'll need fire arrows as well, and will have to snipe the middle dungeon warp pot with a fire arrow. It's in the alcove up and across from the giant head stone that makar is trapped behind in vanilla. You *can* hit it, people sometimes do it when speedrunning or racing or something like that. It's a hard shot though. Once you hit that, go back to the beginning of the dungeon and enter the first warp pot, go back through the door that's next to the middle warp pot, and you'll be in the room with the chest that has bombs in it.

Hope all of this was comprehensible. Good luck!

**Comment by KLPD123** [comment]
Thank you for the quick reply! I tried to do the leaf pumps and I made it to the room you mentioned but there isn't a switch on the other side, it is a deku leaf spin dial thing. The arrows are located on eastern fairy island, helmaroc king heart container, and a frozen chest in the ice ring. Perhaps I can do the glitch where you take out your wind waker to stop the effects of wind for a little while and inch my way to the hole. I learned that by spin attacking frozen chests the ice starts to melt. I will try this and let you know (i think the chest that has the arrows is actually the one outside of the secret cave which I can't access but we will see).

**Comment by KLPD123** [comment]
Upon destroying the ice, the enemies don't unfreeze. Unfortunately I guess this seed is unbeatable :(. That's okay, I will just have to use a cheat code to jump up to the final withered tree. I didn't want to resort to that, but I have nothing.

**Comment by JarheadHME** [comment]
Unfortunately while you are correct in that spinning slowly melts ice, it doesn't allow you to open it, making that chest off limits. What you can do is you can get skull hammer (if you haven't already), sit on your boat in front of the forsaken fortress entrance and let the canons blow up the entrance for you, go in and fight helmaroc (assuming you have a master sword to kill phantom ganon with, if not there's a way around it, it's just kinda a pain), get one there, then for the one in eastern fairy you're gonna have to do door cancel (I mean theoretically you could do it with chest storage but idk if you have any chests left to store).

So the best way I can describe it is go to windfall. go to the rocks to the right of the gate from where the boat normally spawns ([these ones](https://i.imgur.com/ILSqGng.png)), pull out the wind waker in your hand, and you're gonna have to do two very closely timed inputs. When you're finishing climbing up the rock, press the button the wind waker is on, and if timed right link will start falling with the wind waker in his hand. Once he's done that, you need to press b to cancel it when he hits the ground (this one is frame perfect). If you do it right, the wind waker hud will go away but link will still be in the pose. Press b again and you'll have something called storage. If you pull the wind waker out again you'll get something called camera lock, but that's not what we want right now. 

Talk to KoRL (boat), and it should look like it starts some sort of text thing, and then immediately cancels it. Then go to any swinging door on the island and open it, and the text should pop up again. Clear the text when link is in the middle of swinging the door open, and it should cancel the door. Now you have collision that is really messed up and lets you walk through basically all walls. 

Now you'll notice the screen stays black. This is a side effect of opening the door. You can still kinda see where you're going using the minimap, and if you pause or pull up the sea chart you'll have normal vision for a brief moment to orient yourself.

So what you do with this is you go back to the boat, jump into him and sail to the eastern fairy island. Again use the pausing and sea chart to see where you're going. once you get to the island, you should be able to simply walk through the wall of the fairy shell thing and into the hole, which will fix your vision and put you into the fairy hole. After that you can obviously get your second bow upgrade, and you will probably need to save and quit to get out the shell. 

So then you should be able to do the above mentioned things!
