### ISSUE TITLE
Softlock concernin Darknuts

### ISSUE THREAD

**Issue by VriskWhisk** [LagoLunatic/wwrando#108]
Orca holds the Iron boots via Knight's Crest requirement, however, in my state, it seems that if you make the Knight's extinct before obtaining the requirement, it seems you softlock.

Wind Waker Randomizer Version 1.5.0
Permalink: MS41LjAAU3VwcmVtZUlucXVpc2l0aXZlTGluawD//z8EHwACAgE=
Seed: SupremeInquisitiveLink

[WW Randomizer.zip](https://github.com/LagoLunatic/wwrando/files/2838294/WW.Randomizer.zip)

Inside the Zip contains the GCI, a save state of my most recent progress and the spoiler log. Unless there is some method to break the wind stone from Gale Isle without iron boots or some way to possibly enter the Shark Island cave, I'm a little stumped.

**Comment by LagoLunatic** [comment]
There are respawning darknuts in savage labyrinth, which seem to be the ones you'll need to kill on this particular seed. 1 on floor 27 and 2 on floor 30, and you don't need to go farther since you only need 2 knight's crests.

There's 4 places with respawning darknuts in the game, the randomizer assures you can access at least 1 of the 4 before it puts required items on Orca.
