### ISSUE TITLE
Quest States seem inconsistent + misc issues

### ISSUE THREAD

**Issue by KevinTyrrell** [LagoLunatic/wwrando#113]
- Outset Island should have a whirlpool behind it with the door sealed. This should require the bombs to complete. Enterting Jab Ju's domain should yield a random item.

- Entering the swordsman's house on Outset Island should begin sword training, where after completion yields a random item. Currently he is in the 'hurricane spin unlocking phase' by default.

- Two prince komali's exist on Dragon Roost Island at the same time.

- Aryll should exist at the top of the lookout waiting to give link his birthday present, yielding a random item.

- Winds Requiem should be a core item such as the Bow, Hookshot, etc.

- No pirates are present in the pirate ship at Windfall Island

- It is inconsistent that the Wind's Requiem on the stones at Dragon Roost does not yield a cutscene (not sure if I am mis-remembering) while cyclos' defeat yields a cutscene

- Windfall Island should not be in its 'second' state until forsaken fortress 1 has been defeated

- An option to opt out of Ballad of Gales should be added. Gales is a progression item because it is the only way to access Mother and Child isles.

- When arriving at DRC, the Mail Bag cutscene does not play. No item is awarded. Medli is not in her room. Komali is outside.

- Song of Passing should not be given by default. It is a progression item. Players who desperately need to change the day night cycle can travel in the sea for a few minutes. (it's very unlikely that someone cannot do anything else except say.. the auction house on windfall)

- Endless night should be incorporated somehow.

...

**Comment by LagoLunatic** [comment]
> - Outset Island should have a whirlpool behind it with the door sealed. This should require the bombs to complete. Enterting Jab Ju's domain should yield a random item.

This will be the case in the next version.

> - Entering the swordsman's house on Outset Island should begin sword training, where after completion yields a random item. Currently he is in the 'hurricane spin unlocking phase' by default.

Intentional.

> - Two prince komali's exist on Dragon Roost Island at the same time.

This is fixed in the next version.

> - Aryll should exist at the top of the lookout waiting to give link his birthday present, yielding a random item.

Maybe, I'll see if it's possible.

> - Winds Requiem should be a core item such as the Bow, Hookshot, etc.

By "core item" do you mean it should be randomized? No, not doing that.

>- No pirates are present in the pirate ship at Windfall Island

The only pirate present in the second instance of the pirate ship is niko. I had to remove him to get rid of his cutscenes.

>- It is inconsistent that the Wind's Requiem on the stones at Dragon Roost does not yield a cutscene (not sure if I am mis-remembering) while cyclos' defeat yields a cutscene

Can't really remove the cyclos cutscene. He teaches you what note directions to play with his animation moving on the cloud. I don't want to assume players have perfect memory from when they last played wind waker 15 years ago or whatever, so the song tutorials have to stay in. The zephos cutscene on the other hand was pointless and just long and annoying.

>- Windfall Island should not be in its 'second' state until forsaken fortress 1 has been defeated

This is impossible to do without having the game crash due to animation sets and it's not desirable anyway. The randomizer doesn't work well unless the game is in the post-FF2 open world state.

>- An option to opt out of Ballad of Gales should be added. Gales is a progression item because it is the only way to access Mother and Child isles.

True, but that's the only 1 location it helps access. And having BoG at the start is an enormous time save.

>- When arriving at DRC, the Mail Bag cutscene does not play. No item is awarded. Medli is not in her room. Komali is outside.

Intentional.

>- Song of Passing should not be given by default. It is a progression item. Players who desperately need to change the day night cycle can travel in the sea for a few minutes. (it's very unlikely that someone cannot do anything else except say.. the auction house on windfall)

This is how it worked in earlier randomizer versions. It's just annoying, having to find SoP doesn't add any fun.

>- Endless night should be incorporated somehow.

Why? All cutscenes and event states are removed in the randomizer so I don't see much point.
Endless night gave 2 items in vanilla, bombs in the pirate ship and nayru's pearl in jabun's cave. As of the next version both of those items are randomized so I don't see what else endless night could give even if it was added.
Also, I doubt it's possible. It would likely mess with the game's event state too much.
