### ISSUE TITLE
Unable To Leave Phantom Gannon Fight at FF

### ISSUE THREAD

**Issue by XerShade** [LagoLunatic/wwrando#12]
Not sure if this is possible but can you remove the trigger that stops you from getting on the King of Red Lions during the Phantom Gannon fight at Forsaken Fortress. I was playing around trying to kill him without the master sword and the only way to "leave" the fight was to die, void, or save and quit.

If you try to get on the King he tells you to "trust in the master sword" and won't let you leave.

**Comment by LagoLunatic** [comment]
I tried removing that trigger at one point but you still can't leave because phantom ganon spawns a forcefield blocking the exit.
I'm also not sure how well the game would handle it if you did leave, could cause bugs.

All the other minibosses have the same issue of trapping you anyway, none of them are fixable as far as I can see.
