### ISSUE TITLE
[Suggestion] Set custom number of required dungeons for Race Mode

### ISSUE THREAD

**Issue by TheHans255** [LagoLunatic/wwrando#121]
Right now, Race Mode is baked to put progress items in 4 dungeons, and the code for the items randomizer seems to have this set as a constant. Do you think we could get this as a settable range between 1 and 6?

For 5- and 6-dungeon races, there is currently a failsafe to add bow upgrades and the Hookshot in case the player started with all 8 Triforce Shards, and this should probably be extended to also add the Grappling Hook and Boomerang (both of which are logically required in Ganon's Tower, but aren't needed to complete Earth and Wind Temples or Forsaken Fortress) so that all six dungeon rewards can be filled in this case.

Are there any issues with 1- to 3-dungeon races that should be accounted for?

If you're OK with this change conceptually, I can implement it.

**Comment by wooferzfg** [comment]
For 6 dungeon races, the worst case scenario is when you start with 8 shards and do swordless mode. You'd need to place 3 bow upgrades, Hookshot, Grappling Hook, and Boomerang.

For 1 dungeon races, the main issue is that the other 5 dungeons would be banned from having items. In dungeons only mode, this means very few total available progress locations.

**Comment by Compynerd255** [comment]
> For 6 dungeon races, the worst case scenario is when you start with 8 shards and do swordless mode. You'd need to place 3 bow upgrades, Hookshot, Grappling Hook, and Boomerang.

I do mention the six dungeon case (in many words) in my original post. It is a little unfortunate that the Boomerang would have to be placed as a dungeon reward in this case (since it isn't technically required), but it could probably still be allowed since it isn't technically broken. And actually, since all six dungeons are required, a few more items also become required and are available for placement (such as Skull Hammer for FF/WT and Bombs for FF/TofG).

> For 1 dungeon races, the main issue is that the other 5 dungeons would be banned from having items. In dungeons only mode, this means very few total available progress locations.

Ooh, not to mention that the only required dungeon you could have in that case would be Dragon Roost Cavern, since every other dungeon has entrance requirements. In that case, we would either want to set the race mode minimum to 2 dungeons, or have smarter error handling, such as showing an error message to the user that the seed could not be generated, or placing the remaining unplaced items into the starting inventory.

**Comment by Compynerd255** [comment]
Another note: if Tower of the Gods is required (which it certainly will be in a six dungeon race), then so are the three Pearls, which means they can be placed as dungeon rewards in the other five dungeons. This means that we won't have to worry about placing more useful items such as the Grappling Hook, Hookshot, and Boomerang.

In fact, in 2- to 5- dungeon races, it might be worth it to force Tower of the Gods to be required if more dungeon rewards are needed, so that instead of having to place useful items as dungeon rewards, we can place pearls.

**Comment by wooferzfg** [comment]
Placing pearls as dungeon rewards would mean that Tower of the Gods would always be unlocked really late, resulting in there being very few items in the dungeon besides the boss reward.

**Comment by Compynerd255** [comment]
> Placing pearls as dungeon rewards would mean that Tower of the Gods would always be unlocked really late, resulting in there being very few items in the dungeon besides the boss reward.

That is a good point. I did have a thought that maybe placing one or two pearls would help to balance out the issues with placing Boomerang and Grappling Hook, but then if I did that, people would wonder why we don't place all three, so it's probably better to place items.

Of course, all of this is a really niche edge case anyway - all dungeons race, 8 Triforce pieces, _and_ swordless sounds more like a torture run that people would only do once for laughs. Players actually doing All Dungeons competitively would likely be sure to make all of those dungeons have Triforce shards.

As an aside about the 1-dungeon case (race mode, dungeons only), the randomizer actually produces an error message saying that it could not prevent items from being placed in unselected dungeons. Granted, it's not the friendliest error message and can probably stand to be caught earlier (perhaps by adjusting the "# of possible locations" indicator at the top), but it still does prevent a seed from being generated.
