### ISSUE TITLE
[Bug?]Second Maritime Battle Song at Jabun Cave

### ISSUE THREAD

**Issue by OlafurKrH** [LagoLunatic/wwrando#133]
So two things about that. The song that plays during certain parts, such as the whirlpool at Jabun cave had two weird things happen for me. First off, for no real reason I just jumped into the middle of it, losing it immediately and spawning back in front. The music kept playing and the Outset Island song was playing at the same time. Sailing to the sea, the song didn't stop. Going back into the whirlpool, the Outset Island song kept going. The other song stopped when I finished the whirlpool but still wow.

It was funny, but I don't think it's supposed to be like that.

**Comment by LagoLunatic** [comment]
Could you record a video of this, or explain exactly what steps to take to reproduce this?

**Comment by OlafurKrH** [comment]
I just sailed to the whirlpool near Jabun Cave and pressed R to jump straight into it and basically "lost" by reaching the middle of it. I did make a new file to try it again and looking at it closer, it doesn't seem to happen everytime, but yeah that happened with me.

**Comment by bendashie** [comment]
I know this is a few months old, but I got back to doing runs again, and I can confirm that this glitch occurs. However I noticed that it only happens when entering the whirlpool during the daytime, _while_ Outset Island's music is heard in the background. The glitch does not occur when the whirlpool is entered during the nighttime, nor when The Great Sea's music can be heard in the background (this can be done when approaching the whirlpool from the south).
Perhaps the game simply gets confused when those parameters are met since, during normal play, the whirlpool is inaccessible during daylight? I'm not sure, but those are the details I observed while playing. Hope that helps.
