### ISSUE TITLE
[Suggestion] Filter out unimportant options from settings.txt and spoiler logs

### ISSUE THREAD

**Issue by JarheadHME** [LagoLunatic/wwrando#135]
I seem to have gotten this working on my end, but I want to see if anyone else likes this before I commit it. Personally it kinda annoys me that the settings.txt and spoiler logs get a ton of space filled up by the randomized gear block. Not that big of a deal, sure, but still a bit of an annoyance, at least to me.

**Comment by LagoLunatic** [comment]
I think it's okay as long as the only thing being filtered out are non-boolean values that are in their default state.

For example, custom colors that are unchanged from vanilla Link's colors, and randomized gear items that are randomized by default.
It'll need to specifically check if each entry is default or not though, it shouldn't assume an item is default if it's in the randomized_gear list for example (since in the future it could be changed so that there are items that are starting gear by default instead of randomized).

**Comment by JarheadHME** [comment]
Hm, would it be better to filter out default options out of just the spoiler log or filter it out of settings.txt as well? Personally I feel it'd be easier if the settings just maintained everything that's not a complement of something else (i.e randomized gear) or a useless setting to keep track of (the glitch selection box that's to be added later, since it will only store the blank selected item), but filtering the rest out of the spoiler logs I'm all for.

**Comment by LagoLunatic** [comment]
I don't see a point in removing anything from settings.txt. It's possible to calculate the missing values by taking the complement and whatnot but it's easier to code just loading settings.txt as is I think. And it's not like settings.txt is something anybody looks at so it doesn't need to be pretty.
