### ISSUE TITLE
Adjustment to spoils trading logic

### ISSUE THREAD

**Issue by UncleZeldo** [LagoLunatic/wwrando#141]
I made this suggestion on the tracker's github page, but WooferZFG suggested it should be made here instead, because the tracker follows the randomizer's logic.

The grappling hook is listed as a required item for some spoils trading events where it isn't actually required. Examples: green Chu Jellies, Joy Pendants, Skull Necklaces, and Golden Feathers. Having the grappling hook makes farming some of these items easier, but it isn't actually required for any of them.

This isn't just academic. Picking up green Chu Jellies in the first room of Forbidden Woods is trivially easy. Kill Chu, pick up green jelly. Working your way through the dungeon almost guarantees picking up more than 15 of them, unless you're actively trying to avoid them. 

I've also had more than 20 joy pendants before getting the grappling hook in a couple of playthroughs, when I've had a lot of combat prior to getting the grappling hook. Platforms, submarines, secret caves like Shark Island's and Overlook's.

Honestly this seems like more of a tracker issue to me, since it could make novice players think they are unable to trade spoils, even if they have (for example) 15 green jellies or 20 joy pendants. But if the tracker must follow the logic listed in macros.txt, then maybe macros.txt should be updated to reflect the actual gameplay.

**Comment by LagoLunatic** [comment]
I'm not removing the grappling hook requirement. While it's true that in some seeds you will easily get the spoils without using grappling hook, that's not true of every seed. Doing forbidden woods for example requires items to get into and forbidden woods, killing bokoblins to get joy pendants requires a sword if you want to kill them without too much trouble, etc.

The reason grappling hook is listed as a requirement is not because it's literally required, but to make sure that getting the necessary spoils is never an enormous pain in the ass, even in the worst case scenario (e.g. farming 40 joy pendants off bokoblins when your only weapon is bombs for instance).
