### ISSUE TITLE
1.6.0 - progression item in unselected location

### ISSUE THREAD

**Issue by MEGAtheguy** [LagoLunatic/wwrando#143]
![image](https://user-images.githubusercontent.com/12264494/59959029-c47f2300-947d-11e9-8c02-5a3ae051681b.png)

**Comment by LagoLunatic** [comment]
"Progressive" and "Progression" are completely separate concepts.

Progression means the item may be required to beat the game.

Progressive means the item will upgrade itself to the next tier when you get it. For bomb bags, it means you'll always get 60 first, then 99, instead of being able to get 99 and then downgrade to 60. Bomb bags are not progression.
