### ISSUE TITLE
This is the most cursed seed and I’ve never been so upset in my life

### ISSUE THREAD

**Issue by ImSoAngryIMadeThis** [LagoLunatic/wwrando#153]
MS42LjEAVGFycnlTdWJsaW1lTmVydmUA//8/wQdIIAEAAAAAAA==

This seed, this seed right fucking here. 
It’s swordless and everything is randomized. Right off the bat you can get grappling hook from Tingle, this is your peak. It only goes downhill from here. About a couple more hours in and you’ll find that a tower by horseshoe island has the leaf. This is a slight mood lifter, as you would think that maybe things will pickup a little.
Spoiler alert: No
The problem is that the sword is no where to be found, so killing enemies is impossible unless they hit each other or there’s enough pots and barrels around to throw at them. 
I was able to bypass a lot of combat doing this. I even did a WW fall just to get into Forest Haven in the hopes that there would be an item I could kill enemies with. Nope. 
So I started tracking everything I had done up to this point. And it left around 7 or 9 possibilities left as to how I could get an item to progress the run. 
Either I wait for 2 separate mail events to show up, I grind out the Joy Pendants, I grind out the skull necklaces, I grind out the golden feathers, or I grind out the green and blue jellies. I already got to 21 pendants. And I still hadn’t got anything to progress the game. 
My acquired items were as followed:
3 tingle statues
3 triforce shards
Grappling Hook
Leaf
Spoils Bag
Blue Orb
Moblin Letter
Moms Letter
THE FUCKING BOAT SHOP COUPON
Boss keys to the earth, wind, and forest temple
5 triforce charts (without a wallet big enough to decode them)
And around 10 treasure charts
I played this seed for 6 hours straight on stream trying to understand what I was doing wrong. I’m not certain if it’s broken or if I have to grind it all, but please, make sure this seed just cannot happen. This is my only wish.

**Comment by OlafurKrH** [comment]
First off, I tried copying your seed and noticed you didn't generate a spoiler log. That would have been really useful to help out. Checking it would just change the seed somewhat. Now, here are a few things.

1. You can use barrels and jars to knock enemies off the platforms.
2. Can you reach Dragon Roost Cavern and make it past the first locked door? If so, you can use the leaf to glide down towards the boss key chest.
3. Use the shield to knock the sticks off of bokoblins
4. Use a tracker, it always helps out.

**Comment by LagoLunatic** [comment]
>It’s swordless

>The problem is that the sword is no where to be found, so killing enemies is impossible unless they hit each other or there’s enough pots and barrels around to throw at them.

That's what swordless is. No swords in the game. It's a challenge mode, so if you don't want to kill enemies in weird ways like throwing barrels at them you shouldn't use it.

>I even did a WW fall just to get into Forest Haven in the hopes that there would be an item I could kill enemies with. Nope.

The randomizer never requires you to do glitches to progress for the record.

>I played this seed for 6 hours straight on stream trying to understand what I was doing wrong.

As OlafurKrH said generating a spoiler log would have saved you a lot of frustration. I'm not sure why you didn't generate one, since that option is on by default and I only intend for it to be turned off for races to prevent cheating. Here's the spoiler log for your seed, I generated it with magic dev powers.
[WW Random TarrySublimeNerve - Spoiler Log.txt](https://github.com/LagoLunatic/wwrando/files/3590608/WW.Random.TarrySublimeNerve.-.Spoiler.Log.txt)

Also, [here](https://www.wooferzfg.me/tww-rando-tracker/) is a link to an item and location tracker you should use if you don't have all the locations memorized.

>I’m not certain if it’s broken or if I have to grind it all, but please, make sure this seed just cannot happen. This is my only wish.

Why should I prevent this seed from happening? You selected literally every location option including sunken treasures and farming for spoils, it's pretty clear it would result in absolute hell on earth.

That's why the location options exist in the first place - it was obvious on the very first beta test run of the randomizer that no one would play it if progression could be anywhere (especially without a tracker).

The only way I even could prevent it is to detect when the user selects all these options and actually refuse to let them randomize with those settings, but I feel like there's probably one person on planet earth who actually enjoys playing with every setting so I can't really do that.

**Comment by OlafurKrH** [comment]
> I feel like there's probably one person on planet earth who actually enjoys playing with every setting so I can't really do that.

Just for the record, I am that person. Well, except Swordless, I randomize the first one instead.

**Comment by ImSoAngryIMadeThis** [comment]
Thanks for the responses! I’ll admit I was very rude and hasty, if it didn’t come across as funny like I intended. 
Just for the record, I am also one of those people who enjoy every setting on for the most part. I was having fun thinking up ways to beat the enemies. About an hour after I got the leaf though, it went downhill. 

My older brother and I usually race against each other using the same seed and stuff like that. Which is why I don’t generate spoiler logs (plus I just like the challenge). 

The big issue is that for the biggest parts of progression, you need an item that can actually kill enemies. Trust me, it’s not because I don’t like throwing vases around (because what Zelda player would hate that), it’s because 90% of all the caves and other locations that I can access currently require me to be able to kill enemies without pots or grabbable weapons. 
For example: You technically can’t even get into Forest Haven with only the leaf and grappling hook. The first swing is blocked by a plant and you can’t just grapple over him because it doesn’t reach. So I WW fall under the structure to get in. 
Then from there, you can’t get to the temple entrance either because you need to be able to break the grass to replenish your magic meter and you can’t do that either because the leaf and grappling hook are unable to do so. 

Like, I’m gonna have to spend at least an extra hour or two just grinding out jelly and 20 joy pendants. Or even the golden feathers, who knows. 

So would it be possible to say if the option swordless is chosen, that an item which deals damage and can kill enemies (Bow, Bombs, Hammer, Sword, etc) can be made to be randomized within a chest that is readily accessible, rather than side quests which require quantities of items 20 or greater to acquire?
I don’t know how the code looks, but would it be possible for you?
I know it wouldn’t be truly random, but that’s a lot of grinding to do just to actually play the game.
I’ve done multiple every setting playthroughs and by far this is the most vile, and cursed way it’s been randomized that isn’t bugged. 
Once again, I didn’t mean to come off as rude or anything. It was more of an attempt to joke around about the seed.

**Comment by LagoLunatic** [comment]
Are you aware that the grappling hook can be used on enemies to steal their spoils without killing them?
If not that's likely what your issue is. Farming dozens of spoils by killing the enemies is tedious, even with a sword, and must be hell without one. So the randomizer never forces you to do a spoils trading quest that requires more than 1 spoil until you have grappling hook to do it this way.

**Comment by ImSoAngryIMadeThis** [comment]
Yeah no I’m aware of that. I did all those grind quests. That led me to the magic upgrade, which I was able to use to get the flight control platform reward and everything. 

Using the tracker, I’ve exhausted every quest, platform, and sub. I’m gonna check the spoiler logs and I’m gonna hate myself for it but I need to find out. I exhausted like every option I’ve had

**Comment by nbouteme** [comment]
I've checked the spoiler log and I don't see how he's supposed to get the bombs and the boomerang. It might be a bug.

**Comment by LagoLunatic** [comment]
Somebody else commented

>I've checked the spoiler log and I don't see how he's supposed to get the bombs and the boomerang. It might be a bug.

and then deleted their comment which I guess means they changed their mind but I'm gonna answer it anyway since the solution isn't exactly obvious.

* Get Triforce Chart 4 from one of the platforms near Horseshoe Island.
* Use it to salvage the Boomerang from near Overlook Island.
* Use the Boomerang to destroy the cannons on the lookout platforms around Rock Spire Isle in order to get the Hookshot.
* Get Command Melody from Forbidden Woods. Getting into Forbidden Woods requires either Boomerang to cut the grass and refill your magic or double magic meter because you run out of magic otherwise. Once inside you can beat the boko baba on the way with Boomerang (but if you did this before Boomerang you would need to use the Deku Leaf + Grappling Hook combo to kill it instead).
* Get Iron Boots from flying around the outside of Dragon Roost Island. Again you need Boomerang or double magic so you don't run out of magic.
* Now you can get Triforce Chart 3 from Wind Temple. You need Hookshot to get into Wind Temple, Command Melody, Iron Boots, and Deku Leaf to progress, and Boomerang to cut the grass in the cyclones room and refill your magic meter as you're passing through (even if you have double magic it still needs to be refilled). Alternatively, instead of going through the cyclones room you can use Hookshot to go upwards the other path and then use Deku Leaf to glide down to the button that opens the floor, though you'll have to kill the Blue Bubbles along the way using Deku Leaf or Hookshot to stun them, then Grappling Hook to kill them.
* Finally, salvage Bombs from Cliff Plateau Isles.

So yeah, the seed is hell. Still don't think this is an issue though, the options let you choose the the maximum difficulty the seed might be, and in this case it was just bad luck with the randomization that the seed is way harder than average for these settings, but it's not surprising this is possible. Seeds even worse than this should theoretically be possible with the hardest settings. If somebody doesn't want a seed this long and complicated they can uncheck some stuff like sunken treasures, spoils, and swordless, and the maximum difficulty will go down to a more reasonable level.

Also: Always use the tracker from the start and generate a spoiler log
