### ISSUE TITLE
Forsaken Fortress Item Requirement 

### ISSUE THREAD

**Issue by Rixuous** [LagoLunatic/wwrando#161]
In the Forsaken Fortress, it is marked that you cannot get to the 'Chest Outside Upper Jail Cell' without either the hook-shot or the leaf, but getting caught by the Floormaster in the middle room with the hanging boat will throw you in the upper jail cell, which you can then proceed to escape from and grab the chest. So technically it is possible to get this as soon as you get the hammer and bombs. I ended up figuring this out after finding it had the item I needed in the spoiler log, with nowhere else to go.

**Comment by LagoLunatic** [comment]
It's been mentioned before, but I don't think this should be required by the logic since the player has no way of knowing that the FF floormaster behaves differently from all other floormasters and takes you to jail instead of the entrance to the dungeon. Since it's illogical it could be frustrating for someone to figure it out.
