### ISSUE TITLE
[Suggestion]- Some cool ideas

### ISSUE THREAD

**Issue by Nevik9191** [LagoLunatic/wwrando#165]
I had a few neat ideas I wanted to toss out there. I doubt all would be possible but it would be neat to see a few of them.

Din, Farore, and Nayru's pearls should be required before entering the tower of the gods. right now as far as I know they don't really have a use as the tower is already open.

It would be cool if you could choose to not have some of the items you are forced to start with like the sail, songs, and Windwaker. They then could get added into the randomized pool. I.e just have them in the left side of the starting items menu by default.

I think it would be really cool as well to see a randomize every entrance feature. One that makes every entrance lead to somewhere else. It would probably be a nightmare to implement (or completely impossible) but i think it would be really cool. Even just switching  the insides of houses and buildings to different places, or switching rooms in a dungeon around.

Thanks for all the work you guys do.

Edit: forgot to mention is there a reason the joy pendant the killer bees tell you is in the tree, isn't randomized? I totally think it should be added.

**Comment by LagoLunatic** [comment]
>Din, Farore, and Nayru's pearls should be required before entering the tower of the gods. right now as far as I know they don't really have a use as the tower is already open.

This is already the case. The tower doesn't raise itself until you have the 3 pearls.

>It would be cool if you could choose to not have some of the items you are forced to start with like the sail, songs, and Windwaker. They then could get added into the randomized pool. I.e just have them in the left side of the starting items menu by default.

Those items are always given to you for a reason, either because not having the item just makes things more tedious (song of passing), or because the randomizer's logic can't properly take the lack of the item into account (sail).

>I think it would be really cool as well to see a randomize every entrance feature. One that makes every entrance lead to somewhere else. It would probably be a nightmare to implement (or completely impossible) but i think it would be really cool. Even just switching the insides of houses and buildings to different places, or switching rooms in a dungeon around.

Already exists: <https://github.com/CryZe/WindWakerBetaQuest>
Doesn't seem fun so I don't intend to implement it into the randomizer

>Edit: forgot to mention is there a reason the joy pendant the killer bees tell you is in the tree, isn't randomized? I totally think it should be added.

Tried randomizing that at one point, it bugs out for certain items you get there and I don't know how to fix it. It's also a pretty obscure location that I think most people wouldn't be aware exists so it's probably for the best anyway.

**Comment by Nevik9191** [comment]
Awesome thanks for responding I just found out about the pearl thing today. Thanks again!
