### ISSUE TITLE
Customizable logic

### ISSUE THREAD

**Issue by KLPD123** [LagoLunatic/wwrando#169]
Is there a way to customize the logic ourselves/add a gui in the randomizer to change requirements for certain items? Asking because I'd like to try a no logic version :)

**Comment by LagoLunatic** [comment]
You can run the randomizer from source and modify the logic files. Or just modify the code to make it not care about logic at all if you want no logic.

I won't add a no logic option to the GUI since people will probably select it without understanding what it is and then complain about unbeatable seeds. I also don't know why anyone would want no logic.
