### ISSUE TITLE
[Suggestion] Read in custom logic files

### ISSUE THREAD

**Issue by mmtrebuchet** [LagoLunatic/wwrando#205]
Since the logic files are plain text, it'd be nice to have an option to load custom logic files into the randomizer without running from source (and all the package management that entails). After giving up on a seed that shoved me into Shark Island Cave with only a boomerang and four hearts, I'd like to set the logic for my runs to require a sword to kill darknuts. 

Another way to do this would be to have another "tweaks" tab with some of the following options:

- Sword/LightArrows required to kill Darknuts.
- Bottle required for Savage Labyrinth 50.
- Savage Labyrinth 30 requires ability to beat 50. 
- Rainbow Rupee is third progressive wallet.
- Don't require using enemy weapon drops.
- 100% mode: All items for 100% category are logically required to beat Ganondorf.
- Gorons give trading quest reward hint and Koroks give withered tree hint.
- Spoils trading NPCs give hints about their rewards.

While it's conceivable to have a bunch more options, letting me manually edit the logic files would be clean, I think. Plus, this would let me make Bird's Peak Rock entrance require Grappling hook instead of Bait Bag and other silly things that wouldn't make sense to add to the GUI.

On that note, it'd be nice to have a way to force rewards in the logic to be duplicatable nonprogress items. For example, I don't want Orca's 500 hit reward to be a heart piece when I'm trying to go for 100%.

Thanks for all the work you've put into this, LagoLunatic! It's given me many happy hours.
Cheers,
MMTrebuchet.

**Comment by LagoLunatic** [comment]
> Since the logic files are plain text, it'd be nice to have an option to load custom logic files into the randomizer without running from source (and all the package management that entails).

I won't allow loading custom logic files in release because then people would use custom files with bugs in them and the bugs would be impossible to reproduce when reported to me. The extra barrier to entry of having to spend a few minutes installing it from source is intentional to prevent more casual players from doing this.

> On that note, it'd be nice to have a way to force rewards in the logic to be duplicatable nonprogress items. For example, I don't want Orca's 500 hit reward to be a heart piece when I'm trying to go for 100%.

Yeah preventing any nonconsumable items from being in those annoying places might be a good idea.

**Comment by wooferzfg** [comment]
Would it be possible to have the randomizer load custom logic files from a `Custom Logic` folder, but only if `settings.txt` is modified manually (similar to what's required to enable randomized music)? That would still add an extra barrier to entry, but it would allow speedrunners to continue using the official release for things like glitched logic.

**Comment by LagoLunatic** [comment]
I thinking changing a single word in `settings.txt` is too low a barrier to entry tbh. It's fine for music rando since that doesn't actually break the game afaik, hiding that option from the GUI is more just to signify that the option is unfinished, not to stop anyone from using it. Enemy rando is source only because that can result in unbeatable seeds.
