### ISSUE TITLE
Crash when fighting Big Octo

### ISSUE THREAD

**Issue by nintendesi** [LagoLunatic/wwrando#217]
Hi, I encountered this crash when fighting the Big Octo at Two Eye Reef, when using the Beta. I'm not sure what may have caused the crash (not beating the Big Octo within the timer, the angle at which I fired the items, etc.), so I made a highlight of the crash from my stream to show what I did to produce the crash, and I also made sure to highlight the information that the randomizer provided about the crash afterwards. I also have attached the spoiler log of the seed here. I hope this information is helpful in finding the bug and fixing it for the future!

Highlight: https://dashboard.twitch.tv/u/nintendesi/content/video-producer/edit/920670308

Spoiler log: [WW_Random_CasualLinka_-_Spoiler_Log.txt](https://github.com/LagoLunatic/wwrando/files/6014145/WW_Random_CasualLinka_-_Spoiler_Log.txt)

**Comment by wooferzfg** [comment]
Here's a link to the highlight (the one in the issue description doesn't work): https://www.twitch.tv/videos/920670308

**Comment by nintendesi** [comment]
Oh, I apologize about that, I see now that link is only viewable to the streamer. Thank you so much for digging that out wooferzfg!

**Comment by LagoLunatic** [comment]
This is weird, apparently some actor's Z position was a NaN, causing it to fail an assertion.
But I can't tell what actor it is since it's all happening in generic functions. And I don't know how an invalid float could be stored to the position either.

Are you using any cheat codes? Or hacks/mods besides the randomizer itself?

**Comment by nintendesi** [comment]
Thanks for the reply. No, I don't use any cheat codes, hacks, or mods besides what the Beta of the randomizer provides (and the character model for Linka in this seed).

**Comment by LagoLunatic** [comment]
Then it's probably not possible to figure out what caused the crash based on this one occurrence. We'll probably need to wait for somebody else to get the same crash and then try to narrow down which actor could have caused it by looking at which actors are present both times, hopefully finding some way to reproduce it.

Also, what are you playing on? Dolphin/gamecube/wii/wiiU

**Comment by LagoLunatic** [comment]
Also FYI you're on an old version of the beta. Can't be related to this crash but thought I'd mention it.

**Comment by nintendesi** [comment]
Interesting, I'll keep fighting the Big Octo when I play the randomizer, and if I reproduce the crash again, I'll be able to share more data here. I always play the randomizer on a Wii. If there's any other information I can provide, feel free to ask!

Also, where may I find the most current version of the beta? It's great to be able to play the newest version of a randomizer and help out with beta testing – I've done that with several other Zelda randomizers before. I thought I had the most updated beta, from what I had found on the page. Thanks again for all the help!

**Comment by LagoLunatic** [comment]
Beta testers can access it in the `#beta-testers` channel of the official discord server. If you're not already a beta tester ask me on discord and I can give you access.

**Comment by TheRikej** [comment]
Happened to me too, while fighting the Octo in Tingle sector. I was using version 1.9.
I aslo include a screenshot of Dolphin error:
![Screenshot_dolphin_octo_crash](https://user-images.githubusercontent.com/85961701/122105515-2b3f3900-ce19-11eb-9d91-4dee5111fcd5.png)

**Comment by LagoLunatic** [comment]
Do you know what you did that caused it to crash? If you have a video it would help to post it, if not try watching OP's video and seeing if you did anything similar/different to that.

**Comment by TheRikej** [comment]
If I recall correctly, I was shooting him with a bow and hit one of the eyes when it crashed? Unfortunately I have no video of it.

**Comment by LagoLunatic** [comment]
Was it the last of the twelve eyes?

**Comment by TheRikej** [comment]
Not 100% sure, but I think there was still one or two more left

**Comment by wooferzfg** [comment]
I just got a similar crash, but I was playing on version 1.0: https://clips.twitch.tv/BitterShortWaffleMcaT-k4GPBpn_zMGjx-X7

**Comment by LagoLunatic** [comment]
If it's happened with Big Octos in three separate sectors, it seems safe to assume it's related to the Big Octo itself.

However, I can't find anything weird the Big Octo actor or the Big Octo's eye actor does in their code that could write an invalid Z position.

**Comment by TheGreatDuck** [comment]
This is a bug within the regular game as well (link included to a vanilla instance). I am interested to know why it happens, but it doesn't have anything to do with the randomizer.

https://www.youtube.com/watch?v=xAgbZ6uPl3o

**Comment by wooferzfg** [comment]
Here's another example of the Big Octo crash: https://clips.twitch.tv/PreciousFancyDolphinPoooound-JrAEyRpKxmuTFHEn

**Comment by wooferzfg** [comment]
It seems like every time the crash happens, it's when an arrow hits the very edge of an eye.

**Comment by LagoLunatic** [comment]
This turned out to be a bug in the vanilla game. For anyone curious, it's caused by the following sequence of events:
* Arrows keep track of which actor they hit as well as which bone within that actor's model they hit. They do this so the arrow can keep itself attached to a specific point on the actor as the actor moves around.
* The arrow tracks these two things separately, in two different ways: which actor it hit is tracked by the function run when the arrow hits something, while which bone it hit is tracked by the function run once per frame while the arrow is moving forward.
* Arrows can sometimes hit two different things at the exact same time, in this case the Big Octo's body and one of its eyes (which are each separate actors from the body).
* The arrow hits the Big Octo's body first. The arrow sets the body as the actor it hit, and one of its bones as the one it hit. The arrow then immediately stopping itself from moving forward any more.
* The arrow hits the eye second. The arrow sets the eye as the actor it hit, but since it is no longer moving forward, it does not update which bone it hit. The arrow now thinks it has hit a body bone inside the eye.
* The Big Octo's body has more bones than one of its eyes do. So if the body bone hit by the arrow is numerically larger than the number of bones in the eye, the arrow can think it has hit an invalid bone that doesn't exist in the eye.
* When the arrow tries to keep itself attached to that bone, it copies the position of the bone. But if the bone doesn't exist it winds up copying random data that isn't an actual position.
* If that random data winds up not being parseable as a valid float (NaN), the arrow's position is now invalid.
* The game engine really doesn't like actors being at invalid positions, so it intentionally crashes itself.

To fix it I just had the actor turn off its ability to hit things the instant it stops itself from moving forward, so it should never change which actor it attaches itself to after the initial attachment.

Big thanks to Fig for providing a TAS input recording of the bug happening since I don't think I ever would've figured it out without that.
