### ISSUE TITLE
Disable Custom Items Oversight?

### ISSUE THREAD

**Issue by ExaltedMagic** [LagoLunatic/wwrando#231]
When using a custom player model and turning on the Disable Custom Items setting, some of the graphics are not correctly reverted to vanilla. In particular, the Power Bracelets and the sword's scabbard both still appear to be using the custom models' graphics.

**Comment by LagoLunatic** [comment]
Hero's Charm, Power Bracelets, Iron Boots, and Magic Armor are not disabled even if you select the option. This is intentional as the vanilla models would look bad on custom player models.

The Hero's Sword's scabbard cannot be disabled because it's part of Link's body model.
The Master Sword's scabbard is separate, so it should be disabled.

**Comment by ExaltedMagic** [comment]
arright fair enough have a good day
