### ISSUE TITLE
[Suggestion] Option to change NPC models

### ISSUE THREAD

**Issue by RydbergQ** [LagoLunatic/wwrando#236]
Hey all, 

I was wondering if it is possible to create an option to change the models of NPC characters. 
For example I recently started a playthrough as Tingle and thought it would be cool if you could change the character model of NPC Tingle to that of Link.
An option to randomize the models of all NPCs would also be fun!

**Comment by LagoLunatic** [comment]
I won't be adding a feature to change models for anything besides the player to the randomizer because it would create huge problems with memory management.

If you want to make your own mod that changes models you're free to do so, and it can probably be used along with the randomizer, just make it clear that any crashes that happen are because of your mod and not the randomizer.
Note that if you do make such a mod, it's not as simple as swapping out models. You have to re-rig the whole model to fit a different skeleton (e.g. rigging Link's model onto Tingle's skeleton). You have to do that manually for each model replacement on each skeleton.
