### ISSUE TITLE
[Suggestion] Disable Map Select when Spoiler Logs are Disabled

### ISSUE THREAD

**Issue by Crain-32** [LagoLunatic/wwrando#301]
The Map Select tweak has no impact on the Random Seed. As such it is possible in a race Setting to cheat by giving the seed to another player who randomizes the Seed with the Tweak Enabled, who can now go around the map and provide useful information.

Proposed Changes: If "do_not_generate_spoiler_log" is `TRUE`, do not apply the Map Select Tweak. When it is set to `FALSE`, it follows current behavior.

**Comment by LagoLunatic** [comment]
The exact same map select behavior can be obtained by using my Gecko cheat code instead of the randomizer's command line argument. I don't see what removing it from the randomizer itself accomplishes, other than giving people a false sense of security thinking that it's now impossible to map select on no-spoiler-log seeds.

Do cheaters gain anything from being able to use map select on platforms that don't support cheat codes?

And I don't think preventing this decreases the chances of someone accidentally leaving map select on, since Dolphin cheat codes can be accidentally left on easily by forgetting about them, but the randomizer's command line argument has to be set each time manually.

**Comment by Crain-32** [comment]
I mean if we allow external tools then there isn't much to talk about. Static Analysis is possible with a modified Winditor, so any protections are a dead end.
