### ISSUE TITLE
Randomize Wind's Requiem

### ISSUE THREAD

**Issue by NurioHin** [LagoLunatic/wwrando#316]
Since Ballad of Gales and Song of Passing now are options for randomization, what about Wind's Requiem?

I know that this issue already exists: https://github.com/LagoLunatic/wwrando/issues/132
But I figured that since the other two songs are added now, there might be a policy change

**Comment by LagoLunatic** [comment]
Wind's Requiem is required for changing the wind direction for sailing. The randomizer is built on the assumption that you can sail in any direction and go to any island, so this wouldn't work.

You could cruise instead of sailing, but that's incredibly slow and boring, so that makes it worse - even if logic for limiting the wind direction you can sail in was added, you can easily break out of this logic, it's just a huge waste of time to do so. (The vanilla game avoids this by confining you within a predefined area of just a few islands and KoRL preventing you from leaving no matter what).

You could suggest that randomizing Wind's Requiem is only allowed when the Swift Sail tweak is enabled so that you can still sail in any direction. But that idea presents a new awkwardness: places where you have to glide outdoors with Deku Leaf in a certain direction. You'd normally need to use Wind's Requiem to set the direction you have to go in. But if you have Swift Sail but not Wind's Requiem you can instead use the ship to set the Wind Direction. This is very inconvenient because whenever you run into one of these places and the wind isn't already in the direction you need, you'll have to run back to your ship, figure out what direction you need to point it, then run back and use Deku Leaf.

Ultimately I don't think that getting the Wind's Requiem after ship+sail makes any sense, for randomizer gameplay to work correctly you're either going to need to get them at the same time, or get Wind's Requiem first (allowing usage of wind crests and Deku Leaf), *then* ship+sail.

**Comment by NurioHin** [comment]
That makes sense to me
