### ISSUE TITLE
Low Health Animation & Beeping Sound at Full HP if Starting HP Changed in Settings

### ISSUE THREAD

**Issue by RecursiveVision** [LagoLunatic/wwrando#387]
Discovered this one by accident. I started a save file with 1 starting heart and the low health animation was properly removed. I haven't gotten any additional hearts yet.

Then today I changed the ISO to start with 9 hearts by default because I wanted to kill a boss to test an event flag and instead of creating a new save file for this test, I accidentally loaded the save for my other playthrough that had 1 heart.

Link immediately started doing the low health animation and the beeping sound was playing, despite Link being at full health.

Seems like the code is grabbing the max HP from the ISO rather than from the save file.

**Comment by Aelire** [comment]
The max HP is grabbed from the save file, but the code is only modified to remove the beep if the ISO is configured to start with <2 hearts; so for an iso starting with 9 hearts the beep behavior is vanilla (starts beeping at 1.5 hearts regardless of the max)

I believe in general (or at least that was my assumption in this code) loading a save from a different ISO is not supported, but otherwise making this line unconditional would fix this: https://github.com/LagoLunatic/wwrando/blob/741401c864b4ea403adcea8eaab856b4860b3882/tweaks.py#L897-L898

**Comment by LagoLunatic** [comment]
Not a bug, loading a save file for a different randomizer seed isn't supported and breaks everything. It can result in much worse effects than this.
