### ISSUE TITLE
First small key for DRC disappeared from inventory after leaving dungeon early

### ISSUE THREAD

**Issue by CarlJMcGee** [LagoLunatic/wwrando#397]
I went to DRC pretty early on in my playthrough to get the first 3 chests. Two had items and one had the vanilla key. Since the tracker said I couldn't do anymore checks in DRC, I marked in the tracker that I had 1 small key, saved and reloaded the save to go back to the beginning of the dungeon and left.

Fast forward several hours and I finally have the grappling hook, so I head back DRC. However my inventory said I had no small keys, which was weird because I remembered getting one earlier. I check my tracker and I had marked down that I had 1 small key. I checked the three chests again and they were all already opened.

So as far as I can tell, I am completely softlocked in that dungeon. The only checks I have available are in DRC, so my rando is dead. I wish I knew when the key disappeared from my inventory, but it was a solid 4+ hours between getting the key and returning to the dungeon, so I really have no idea. 

I haven't seen anyone else experience this online, so I thought I'd submit and issue, but to be honest I'm not sure if there is much you can do given the limited info I can offer. Still, I thought I'd might as well post it.

**Comment by LagoLunatic** [comment]
Post your spoiler log.

**Comment by CarlJMcGee** [comment]
[WW Random ThanklessRomanticObli - Spoiler Log.txt](https://github.com/user-attachments/files/16116450/WW.Random.ThanklessRomanticObli.-.Spoiler.Log.txt)

**Comment by LagoLunatic** [comment]
The reason the only DRC small key you found disappeared is because you used it, and small keys are single-use. If you hadn't used it, you wouldn't have been able to open the other 2 chests you mentioned that had items early in your playthrough.

The next small key you need is in the chest that had the big key in the vanilla game.
You can reach it with ice arrows: https://imgur.com/R0cYujl
The second bow upgrade (fire and ice arrows) is dropped by Helmaroc King, so you have to go to Forsaken Fortress first if you haven't already.

**Comment by CarlJMcGee** [comment]
Ok that make sense. I played through DRC again this afternoon and my memory of the dungeon was wrong, I had forgotten that the first door into the large lava room used a small key. That was my bad. 

Thanks for the quick reply to my stupid question!
