### ISSUE TITLE
Immobile Blocks and Mirrors In Earth Temple

### ISSUE THREAD

**Issue by RandomNumbersGuy** [LagoLunatic/wwrando#57]
Just got to the Earth Temple, and there seems to be a weird glitch where I'm unable to move blocks or mirrors at all, preventing me from accessing certain parts of the dungeon. I thought this may be an intentional design choice to make it more challenging, but I've never seen anyone else deal with this. I have no issues moving blocks in other areas. I very well could be doing something wrong (heck, I probably am), but I don't know what to do. Any help would be appreciated, thanks!

**Comment by LagoLunatic** [comment]
Need power bracelets to move those things in earth temple.
Usually you won't notice this since you need them just to enter earth temple, but with randomized dungeon entrances you can see it.
(And yeah, it's quite interesting that the devs coded those objects to check if you have power bracelets when players of the vanilla game would never know it.)

**Comment by XerShade** [comment]
It's not really that interesting, the blocks and mirror's are created before the dungeons are, and just in case they are used outside the dungeon the properties are coded, its a coding way of ensuring you don't forget to set something should you decide down the line "Hey, I want to use one of those massive mirrors here".
