### ISSUE TITLE
[suggestion/question]

### ISSUE THREAD

**Issue by scratchcaft** [LagoLunatic/wwrando#63]
If there is not one already, might i suggest making an option to randomize enemy locations eg instead of chus darknuts spawn and vice versa? and also is there an option to scramble the islands like moving outset to a 3 and forsaken fortress to e 6? and i love how dungeons are randomized, is there an option for making every door randomized? eg going into dragon roost cavern only to end up in tower of the gods andgoing through a door in there to wind up at the battleship minigame room on outset?

**Comment by LagoLunatic** [comment]
1. I'd like to add an enemy randomizer. I started work on it a month or two ago, but there are a ton of technical issues so it's unclear whether it will ever be playable or not.
2. No
3. I won't add an option to randomize every door, but I will be adding an option to randomize secret cave entrances in addition to dungeon entrances for the next version. Other doors like houses would be no fun at all (neither for the player to play, or for me to implement).

**Comment by scratchcaft** [comment]
Hmmm. Okay then. How does the randomizing of loading zones work anyway? And
one last thing. Would cutting the map into 36 chunks and shuffling them be
harder or easier than loading zones theoretically? I ask out of the quest
for knowledge not out of defiance.

**Comment by LagoLunatic** [comment]
When you say "36 chunks" I assume you meant 49 sectors on the sea?
Shuffling the island sectors around is far more work than changing the loading zones. Lots of different things need to be modified in order for everything in each sector to still work correctly (and that's not counting hurdles I wouldn't know about until actually attempting it). Definitely not worth the hassle of even attempting it.

Shuffling loading zones is fairly easy in and of itself, it's just changing the destination stage/room/spawn on each exit.
The hard part is writing the *logic* to guarantee the game is always completable after loading zones are shuffled. The logic for just dungeons and secret caves isn't very hard since they all have just one entrance accessible from the sea.
The logic for *every* loading zone would take a lot longer, not only because there's more loading zones but because many of them need more complex logic. And you need to somehow figure out how to handle multiple loading zones leading into the same area.
You'd also need to be careful to prevent the player getting permanently stuck in some location. Normally this is impossible in wind waker, because even if you get stuck you can save and quit to return to the sea, or start of the dungeon which leads out to the sea. But with all loading zones shuffled around, the loading zone out of the start of a dungeon might not take you back to the sea and you could be permanently trapped in the dungeon if you don't have the proper items to escape.

**Comment by scratchcaft** [comment]
hmm that makes sense. thank you for explaining and yeah i meant 49, its a 7
by 7 map not a 6 by 6 lol i always forget that without actually looking at
the great sea. so shuffling the islands sounds more complicated than making
an array to pick from containing each sector (obtained by using a duplicate
map to cut into 49 pieces and copying from the original to paste into the
randomizer at diferent locations) and having it randomly place them at set
sizes. the logicand loaading zones and boundaries would definitely throw a
few wrenches into the wors with that.

i just thought of the enemy randomizer and a potential and hillarious
hurdle. wanna hear it?

**Comment by scratchcaft** [comment]
are there gonna be measures in place to stop the switching of darknuts with
miniblins?

**Comment by LagoLunatic** [comment]
Eventually I would probably need to put in some kind of balancing logic to stop stuff like that, though I would probably want to get the enemy randomizer working without crashes or softlocks, and with a minimal level of enemies glitching out (see below) first.

![redead patrol](https://user-images.githubusercontent.com/19174152/48393821-12a99800-e6df-11e8-8c3f-850478c90ef4.gif)

**Comment by scratchcaft** [comment]
and will you implement a savage labyrinth toggle? it would be hilarious if
on the floor with all the chus there were like 20 darknuts

**Comment by scratchcaft** [comment]
which language do you use?
