### ISSUE TITLE
Cutscene items

### ISSUE THREAD

**Issue by LordNile** [LagoLunatic/wwrando#9]
So, I’ve been watching a play through of this and tried it out myself, loving it, but it seems that every item that would appear in a cutscene doesn’t exist. For example; you will find Din’s pearl somewhere in the world, but the normal place for the pearl gives you nothing. Is there specified places that these items are supposed to go, like extra chests that me and the other guy can not find?

**Comment by LagoLunatic** [comment]
Randomizing the items given by cutscenes is impossible because of the way the engine handles cutscenes. Besides, it wouldn't be fun to have to watch a ton of long cutscenes every playthrough. So cutscenes are removed from the game.

2 new chests are added to the game - the DRC mini boss has a chest as a replacement for Medli, and Mother Isle has a chest as a replacment for the Queen Fairy. There's no replacement for the others.
